name: Build Executable

on:
  push:
    branches:
      - main
    paths:
      - 'cipherCli.py'
      - 'cipherUtils.py'
      - 'cipherCli.spec'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller

    - name: Build executable
      run: pyinstaller cipherCli.spec

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: cipherImage-Package
        path: dist/cipherCli.exe
