name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller
      
    - name: Create artifact path
      run: mkdir -p dist

    - name: Build executable
      run: pyinstaller --onefile --noconsole --icon=cipherImage.ico --distpath dist cipherCli.py

    - name: Save txt file to artifact path
      run: ls dist/ > dist/world.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: dist/world.txt

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist/cipherCli.exe
