name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller

    - name: Build executable
      run: pyinstaller cipherCli.spec

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: cipherCli
        path: dist/cipherCli.exe
